# DS210 Lab-3
Name:  
Roll No:  

# Visulization of AMEO

## Why this dataset?
It is a unique dataset which contains engineering graduates’ employment outcomes (salaries, job titles and job locations) along with standardized assessment scores in three fundamental areas - cognitive skills, technical skills and personality.


### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(style="whitegrid", color_codes=True)

pd.set_option('display.max_columns', None)

In [2]:
# Load Dataset
url = "https://raw.githubusercontent.com/deba-iitbh/datasets/main/AMEO_2015.csv"
df = pd.read_csv(url)
df.head()

Salary Gender  10percentage  12percentage 12board       Degree  \
0  300000      m         89.92         87.00   state  B.Tech/B.E.   
1  300000      m         86.08         67.50   state  B.Tech/B.E.   
2  300000      m         81.20         79.90   state  B.Tech/B.E.   
3  250000      m         60.80         66.66    cbse          MCA   
4  335000      m         88.00         90.00   state  B.Tech/B.E.   

  Specialization  collegeGPA  English  Logical  Quant    Domain  \
0             EC       76.32      560      555    620  0.000000   
1             CS       72.98      590      435    380  0.356536   
2             EC       67.67      395      565    645  0.000000   
3             CS       74.74      465      585    515  0.911395   
4             CS       76.00      625      555    630  0.356536   

   ComputerProgramming  ComputerScience  conscientiousness  agreeableness  \
0                  645              407            -0.3027        -0.6201   
1                  405              346             1.7081        -0.1054   
2                  495              376             0.7027         0.7119   
3                  545              500             0.8463         1.0449   
4                  475              346             0.4155         0.8027   

   extraversion  nueroticism  openess_to_experience  12GradAge  GradAge  
0       -2.2954      -0.7415                -0.8608         22       22  
1       -1.0379      -2.0092                -1.0872         23       23  
2        0.0100      -0.9950                 0.6721         22       22  
3       -1.0659      -1.6289                 0.6721         17       17  
4        0.1357      -0.9950                -0.6692         23       23

Create a bar plot of the gender category distribution

Draw a boxplot visualization of salary levels by gender.

create a histogram of salary data

Create a stacked bar graph of salary levels categorized based on 12th board for 2 categories(male and female)

Create a scatterplot show the diustribution of logical skills vs salary

creating new columns -   
Average score - Average score of English, Logical, Quant  
Academic Performace - Sum of all the scores in 10, 12, college

Show the co-relation between salary and Average score (if any)

computer programming skills is very important in recent years,   
show the effect of computer programming skills in salary using a plot

Draw a boxplot visualization of salary and specialization(EC, CS, ME, EL, Other)

# Unsupervised Analysis of MNIST

## Why this Dataset?
Let's be frank up-front. MNIST is the most classical example of a machine learning datatset. One which has been explored quite a number of times by many people and We do not have any novelty to add to the solution. **Unless we try to use an etirely different approach to solve the problem.** Much of the existing work done on this dataset has been using some form of *Supervised Learning*, may it be Linear models or Decision Trees or GBTs or CNNs.  
What we are going to do through this notebook is to find an unique approach to solve this problem through an ***Unsupervised Algorithm***. Sounds novel now? 😎

## Problem Statement
Our goal is to correctly identify digits from a dataset of tens of thousands of handwritten images.  
The scoring metric for this competition is also a classical one for multi-class classification: **Accuracy**.  

### Data Description:-
1. The data files train.csv and test.csv contain gray-scale images of hand-drawn digits, from zero through nine.
2. Each image is 28 pixels in height and 28 pixels in width, for a total of 784 pixels in total. Each pixel has a single pixel-value associated with it, indicating the lightness or darkness of that pixel, with higher numbers meaning darker. This pixel-value is an integer between 0 and 255, inclusive.

### Expected Outcome:-
* Correctly identify the digit form the pixel values of an grayscale image.

## Imports
Keeping these above points in mind, let's start by importing some basic libraries that we require.

In [3]:
# Asthetics
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings('ignore', category=FutureWarning)

# General
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import os
import time
import random
from scipy.stats import mode

# Datasets
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

# Visialisation
import matplotlib.pyplot as plt
from matplotlib import offsetbox
%matplotlib inline
import seaborn as sns
sns.set(style="whitegrid")
import plotly.express as px

# Dimensionallity Reduction
from sklearn.decomposition import PCA

# clustering
# Flat
from sklearn.cluster import KMeans

# Hierarchical
from sklearn.cluster import AgglomerativeClustering

#Metrics
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report

# extra (if you need)

In [4]:
# Load dataset
mnist = load_digits()
X, y, labels = mnist['data'], mnist['target'], mnist["target_names"]
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.1)
print(f"Shape of X_train-{X_train.shape}\nShape of X_test-{X_test.shape}")

Shape of X_train-(1617, 64)
Shape of X_test-(180, 64)


In [5]:
X_train, y_train, labels

(array([[ 0.,  0.,  6., ...,  0.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  6.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        ...,
        [ 0.,  2., 11., ..., 13., 16.,  1.],
        [ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 14.,  2.,  0.]]),
 array([9, 9, 4, ..., 2, 7, 6]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

## EDA

In [6]:
# Plot 10 random images from the dataset

Great! Let's see what is the class balance in this particular ptoblem set...

In [7]:
# Check the class imbalance using bar plot

**Are all the class balanced? what do you think?**

## PCA

PCA is a dimensionality reduction technique. Let's see how those clusters look after PCA...


### 2D PCA

In [8]:
# Apply PCA with 2 components to train data and visualize the points using scatterplot(using both Seaborn and Plotly)

### 3D PCA

In [9]:
# Apply PCA with 3 components to train data and visualize the points using scatterplot(using Plotly)

Now that we have seen various embeddings of MNIST clustered on 2 and 3 axes.
Write 5 inferences from these plots.

1.  
2.  
3.  
4.  
5.  

## T-SNE

### 2D T-SNE

In [10]:
# Apply T-SNE with 2 components to train data and visualize the points using scatterplot(using both Seaborn and Plotly)

### 3D T-SNE

In [11]:
# Apply T-SNE with 3 components to train data and visualize the points using scatterplot(using Plotly)

Now that we have seen various embeddings of MNIST clustered on 2 and 3 axes.
Write 5 inferences from these plots.

1.  
2.  
3.  
4.  
5.  

Another interesting aspect to see is to track what kind of variations are there within a single class... To visualize this better let's create an helpfer function hat will output image thumbnails at the locations of the projections.

In [12]:
def plot_components(data, model, images=None, ax=None, thumb_frac=0.05, cmap='gray'):
    ax = ax or plt.gca()
    proj = model.fit_transform(data)
    ax.plot(proj[:, 0], proj[:, 1], '.k')
    if images is not None:
        shown_images = np.array([2 * proj.max(0)])
        for i in range(data.shape[0]):
            shown_images = np.vstack([shown_images, proj[i]])
            imagebox = offsetbox.AnnotationBbox(
                offsetbox.OffsetImage(images[i], cmap=cmap),
                proj[i])
            ax.add_artist(imagebox)
    plt.show()

Let's plot all of the ones and see how varied are they from one another...

In [13]:
# Use the abhove helper function to visualize the variation with class of digit '1' and '0'

The plots are Fascinating isn't it!  
As you can see this gives un an idea of the variety of Ones we have in out datatset.

Write some inference from the above plot.

1.  
2.  
3.  
4.  

## Clustering

Apply K-Means clustering on the data and visualize it.

Try to plot the Within Cluster Squered Loss(WCSS) for the clustering as well.

Apply Hierarchical Clustering and visualize it using dendogram.

what do you think will be a good threshold for cutting the dendogram and make clusters?  
Hint: Do some experiments.